#!/usr/bin/env python3
"""
Rebuild middleware/store/item-images.js from the product photos in
"SRS/Data List/Item Pictures".

Usage:   python3 build-item-images.py "<path to Item Pictures folder>"
Needs:   pip install pillow

Each photo is padded to a square on white, resized to 180x180, saved as a
small JPEG and embedded as a data URI, so no image hosting is required.
One photo can cover several item codes (size variants share a photo).
To add a new product photo: drop the file in the folder, add a line to
MAP below with its item code(s), and re-run this script.
"""
import base64, io, os, sys
from PIL import Image

MAP = {
    # ---- Head Protection ----
    "DT025 Green.png":                        ["HPHTPE0001"],
    "DT025 Red.png":                          ["HPHTPE0002"],
    "DT025 Blue.png":                         ["HPHTPE0003"],
    # ---- Eye & Face ----
    "Safety Spectacle Clear.png":             ["EFSPPC0001"],
    "Safety Spectacle Smoke.png":             ["EFSPPC0002"],
    "Chempact1.png":                          ["EFGGNY0001"],
    # ---- Respiratory ----
    "SV210 N95 MASK.tif":                     ["RPDM950001"],
    # ---- Protective Clothing ----
    "100% Cotton Coverall, Royal Blue.png":   ["PCCVCT0001", "PCCVCT0002", "PCCVCT0003"],
    "Hot Metal Shirt, Light Blue.png":        ["PCSHHM0001", "PCSHHM0002", "PCSHHM0003"],
    "100% Cotton Shirt, Khaki.png":           ["PCSHCT0001", "PCSHCT0002", "PCSHCT0003"],
    "Hot Metal Trouser, Grey.png":            ["PCTRHM0001", "PCTRHM0002", "PCTRHM0003", "PCTRHM0004"],
    "100% Cotton Trouser, Navy Blue.png":     ["PCTRCT0001", "PCTRCT0002", "PCTRCT0003", "PCTRCT0004"],
    "Hi-Viz Vest, Yellow.png":                ["PCVSPE0001", "PCVSPE0002", "PCVSPE0003"],
    # ---- Gloves ----
    "Heat Resistant Gloves.png":              ["GLHMCT0001"],
    "General Purpose Gloves.tif":             ["GLGPCT0001"],
    # ---- Foot Wear ----
    "General Purpose Safety Boots.tif":       ["FEGPBT0001", "FEGPBT0002", "FEGPBT0003", "FEGPBT0004", "FEGPBT0005"],
    # No photo supplied yet: FWHMBT0001-0005 (Hot Metal Boots, Black) — the app
    # falls back to the emoji icon for these until a photo is added here.
}

SIZE, QUALITY = 180, 78

def main(folder, out_path):
    entries, missing, total = {}, [], 0
    for fname, codes in MAP.items():
        path = os.path.join(folder, fname)
        if not os.path.exists(path):
            missing.append(fname)
            continue
        im = Image.open(path).convert("RGBA")
        w, h = im.size
        side = max(w, h)
        canvas = Image.new("RGB", (side, side), (255, 255, 255))
        canvas.paste(im, ((side - w) // 2, (side - h) // 2), im)
        canvas = canvas.resize((SIZE, SIZE), Image.LANCZOS)
        buf = io.BytesIO()
        canvas.save(buf, "JPEG", quality=QUALITY, optimize=True)
        data = buf.getvalue()
        total += len(data)
        uri = "data:image/jpeg;base64," + base64.b64encode(data).decode()
        for c in codes:
            entries[c] = uri
        print(f"  {fname:42s} {len(data)//1024:3d} KB -> {', '.join(codes)}")

    with open(out_path, "w") as f:
        f.write("/** Real product photos from 'SRS/Data List/Item Pictures'.\n")
        f.write(" *  Generated by middleware/tools/build-item-images.py — do not edit by hand.\n")
        f.write(" *  Padded to a square, 180px, JPEG, embedded as data URIs so no image\n")
        f.write(" *  hosting is needed. One photo covers all size variants of a product.\n")
        f.write(" *  Items with no photo yet (Hot Metal Boots) fall back to the emoji icon. */\n")
        f.write("module.exports = {\n")
        for code in sorted(entries):
            f.write(f'  {code}: "{entries[code]}",\n')
        f.write("};\n")
    print(f"\n{len(entries)} item codes mapped from {len(MAP) - len(missing)} photos, {total//1024} KB total")
    if missing:
        print("MISSING photo files:", ", ".join(missing))

if __name__ == "__main__":
    folder = sys.argv[1] if len(sys.argv) > 1 else "."
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "store", "item-images.js")
    main(folder, os.path.abspath(out))
