#!/usr/bin/env python3
"""
Rebuild middleware/store/item-images.js from the product photos in
"SRS/Data List/Item Pictures".

Usage:   python3 build-item-images.py ["<path to Item Pictures folder>"]
Needs:   pip install pillow

Photos are looked for in the folder given on the command line first, then in
middleware/assets/item-photos/ (photos supplied later and kept in the repo).
Existing entries in item-images.js are KEPT when their source photo is not
available, so the script can be re-run with only the new pictures to hand.

Each photo is padded to a square on white, resized to 180x180, saved as a
small JPEG and embedded as a data URI, so no image hosting is required.
One photo can cover several item codes (size variants share a photo).
To add a new product photo: drop the file in the folder, add a line to
MAP below with its item code(s), and re-run this script.
"""
import base64, io, os, sys
from PIL import Image

MAP = {
    # ---- Head Protection ----
    "DT025 Green.png":                        ["HPHTPE0001"],
    "DT025 Red.png":                          ["HPHTPE0002"],
    "DT025 Blue.png":                         ["HPHTPE0003"],
    # ---- Eye & Face ----
    "Safety Spectacle Clear.png":             ["EFSPPC0001"],
    "Safety Spectacle Smoke.png":             ["EFSPPC0002"],
    "Chempact1.png":                          ["EFGGNY0001"],
    # ---- Respiratory ----
    "SV210 N95 MASK.tif":                     ["RPDM950001"],
    # ---- Protective Clothing ----
    "100% Cotton Coverall, Royal Blue.png":   ["PCCVCT0001", "PCCVCT0002", "PCCVCT0003"],
    "Hot Metal Shirt, Light Blue.png":        ["PCSHHM0001", "PCSHHM0002", "PCSHHM0003"],
    "100% Cotton Shirt, Khaki.png":           ["PCSHCT0001", "PCSHCT0002", "PCSHCT0003"],
    "Hot Metal Trouser, Grey.png":            ["PCTRHM0001", "PCTRHM0002", "PCTRHM0003", "PCTRHM0004"],
    "100% Cotton Trouser, Navy Blue.png":     ["PCTRCT0001", "PCTRCT0002", "PCTRCT0003", "PCTRCT0004"],
    "Hi-Viz Vest, Yellow.png":                ["PCVSPE0001", "PCVSPE0002", "PCVSPE0003"],
    # ---- Gloves ----
    "Heat Resistant Gloves.png":              ["GLHMCT0001"],
    "General Purpose Gloves.tif":             ["GLGPCT0001"],
    # ---- Foot Wear ----
    "Hot Metal Boots, Black.png":             ["FWHMBT0001", "FWHMBT0002", "FWHMBT0003", "FWHMBT0004", "FWHMBT0005"],
    "General Purpose Safety Boots.png":       ["FEGPBT0001", "FEGPBT0002", "FEGPBT0003", "FEGPBT0004", "FEGPBT0005"],
}

# Photos supplied after the original workbook, kept in the repo so the script
# can be re-run without the whole "Item Pictures" folder to hand.
BUNDLED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "item-photos")

SIZE, QUALITY = 180, 78

def existing(out_path):
    """Re-read the photos already embedded, so a partial re-run keeps them."""
    kept = {}
    if not os.path.exists(out_path):
        return kept
    for line in open(out_path):
        line = line.strip()
        if line.startswith(("//", "/*", "*", "module")) or ":" not in line:
            continue
        code, _, rest = line.partition(":")
        rest = rest.strip().rstrip(",").strip('"')
        if rest.startswith("data:image/"):
            kept[code.strip()] = rest
    return kept

def find_photo(folder, fname):
    for base in ([folder] if folder else []) + [BUNDLED]:
        path = os.path.join(base, fname)
        if os.path.exists(path):
            return path
    return None

def main(folder, out_path):
    entries = existing(out_path)
    missing, total = [], 0
    for fname, codes in MAP.items():
        path = find_photo(folder, fname)
        if not path:
            missing.append(fname)
            continue
        im = Image.open(path).convert("RGBA")
        w, h = im.size
        side = max(w, h)
        canvas = Image.new("RGB", (side, side), (255, 255, 255))
        canvas.paste(im, ((side - w) // 2, (side - h) // 2), im)
        canvas = canvas.resize((SIZE, SIZE), Image.LANCZOS)
        buf = io.BytesIO()
        canvas.save(buf, "JPEG", quality=QUALITY, optimize=True)
        data = buf.getvalue()
        total += len(data)
        uri = "data:image/jpeg;base64," + base64.b64encode(data).decode()
        for c in codes:
            entries[c] = uri
        print(f"  {fname:42s} {len(data)//1024:3d} KB -> {', '.join(codes)}")

    with open(out_path, "w") as f:
        f.write("/** Real product photos from 'SRS/Data List/Item Pictures'.\n")
        f.write(" *  Generated by middleware/tools/build-item-images.py — do not edit by hand.\n")
        f.write(" *  Padded to a square, 180px, JPEG, embedded as data URIs so no image\n")
        f.write(" *  hosting is needed. One photo covers all size variants of a product.\n")
        f.write(" *  An item with no photo here falls back to its emoji icon. */\n")
        f.write("module.exports = {\n")
        for code in sorted(entries):
            f.write(f'  {code}: "{entries[code]}",\n')
        f.write("};\n")
    print(f"\n{len(entries)} item codes mapped, {len(MAP) - len(missing)} photos re-encoded ({total//1024} KB)")
    if missing:
        print("Photo file not found (existing entry kept):", ", ".join(missing))

if __name__ == "__main__":
    folder = sys.argv[1] if len(sys.argv) > 1 else "."
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "store", "item-images.js")
    main(folder, os.path.abspath(out))
