#!/usr/bin/env python3
"""
Build the single file the admin runs in Supabase:

    middleware/supabase/setup-all-v3.sql

from the source parts in middleware/supabase/parts/ (migration, schema, seed).
Run this after changing any part, or after regenerating the seed with
    node tools/build-seed-sql.js

Usage:  python3 tools/build-setup-sql.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(HERE, "..", "supabase", "parts")
OUT = os.path.join(HERE, "..", "supabase", "setup-all-v3.sql")

HEADER = """-- ═══════════════════════════════════════════════════════════════════
-- PROSAFE × EGA — DATABASE SETUP  (Mobile App SRS2, 25-08-26)
--
--            ★ THIS IS THE ONLY FILE YOU NEED TO RUN ★
--
-- Supabase → SQL Editor → paste this whole file → Run.
-- It does everything, in order:
--     1. migrates an old (v2) database to the SRS2 model — first run only
--     2. creates/updates every table, function and constraint
--     3. loads and refreshes all master data from the Data List workbooks
--
-- SAFE TO RE-RUN at any time. A repeat run refreshes master data (items,
-- price lists, stores, departments…) and leaves everything else alone:
--     · user accounts and their role / price-list / store assignments — kept
--     · orders, allocations (Used Qty), ERP documents, sequences — kept
--     · live inventory quantities — kept
-- The one-time v2 cleanup only happens while the database is still on the
-- old model (i.e. before the v3 `masters` table exists).
--
-- Expect a batch of "already exists, skipping" NOTICE lines — that is normal,
-- they are not errors.
--
-- Product photos are NOT in this file. The middleware serves them from
-- middleware/store/item-images.js, so nothing here is oversized.
--
-- Generated by middleware/tools/build-setup-sql.py from supabase/parts/ —
-- edit the parts, not this file.
-- ═══════════════════════════════════════════════════════════════════

"""

SECTIONS = [
    ("PART 1 · MIGRATE an old v2 database (first run only)", "migrate-v2-to-v3.sql"),
    ("PART 2 · SCHEMA — tables, functions, constraints", "schema.sql"),
    ("PART 3 · MASTER DATA — load / refresh", "seed.sql"),
]

def main():
    out = [HEADER]
    for title, fname in SECTIONS:
        body = open(os.path.join(PARTS, fname)).read()
        # the parts are also runnable on their own; make the ALTERs tolerant
        # of a database where `profiles` does not exist yet
        body = (body.replace("alter table profiles drop constraint",
                             "alter table if exists profiles drop constraint")
                    .replace("alter table profiles add column",
                             "alter table if exists profiles add column"))
        out.append(f"\n\n-- ╔══════════════ {title} ══════════════╗\n\n")
        out.append(body)
    text = "".join(out)
    with open(OUT, "w") as f:
        f.write(text)
    longest = max(len(l) for l in text.split("\n"))
    print(f"wrote {os.path.relpath(OUT)}  —  {len(text)//1024} KB, "
          f"{len(text.splitlines())} lines, longest line {longest} chars")

if __name__ == "__main__":
    main()
