#!/usr/bin/env python3
"""
Rebuild the Prosafe Systems logo used by the website and the phone app from
the master artwork in assets/brand/prosafe-logo.png.

Usage:   python3 tools/build-brand.py
Needs:   pip install pillow

Writes three things:
    web/src/logo.js        the logo as a data URI (imported by the portal)
    mobile/src/logo.js     the same, for React Native <Image source={{uri}}>
    web/public/favicon.png the round mark on its own, for the browser tab

Embedding it as a data URI means no image hosting and no bundler asset
pipeline — it works the same in dev, in the Vercel build and in Expo.

To change the logo: replace assets/brand/prosafe-logo.png and re-run this.
"""
import base64, io, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MASTER = os.path.join(ROOT, "assets", "brand", "prosafe-logo.png")

LOGO_WIDTH = 420          # 2x the largest place it is drawn, so it stays crisp
FAVICON = 64

def png_bytes(im, colors=96):
    """Flat-colour artwork: an indexed palette keeps the edges clean and makes
    the file small enough to inline comfortably."""
    buf = io.BytesIO()
    im.convert("RGB").quantize(colors=colors, method=Image.MEDIANCUT, dither=Image.NONE) \
      .save(buf, "PNG", optimize=True)
    return buf.getvalue()

def write_module(path, uri, note):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("/** Prosafe Systems logo — generated by tools/build-brand.py.\n")
        f.write(f" *  {note}\n")
        f.write(" *  Do not edit by hand: replace assets/brand/prosafe-logo.png\n")
        f.write(" *  and re-run the script instead. */\n")
        f.write(f'export const LOGO = "{uri}";\nexport default LOGO;\n')

def main():
    master = Image.open(MASTER).convert("RGBA")

    # --- the wordmark, as used in the sidebar, the sign-in card and the app ---
    w, h = master.size
    logo = master.resize((LOGO_WIDTH, round(h * LOGO_WIDTH / w)), Image.LANCZOS)
    data = png_bytes(logo)
    uri = "data:image/png;base64," + base64.b64encode(data).decode()
    write_module(os.path.join(ROOT, "web", "src", "logo.js"), uri,
                 f"{logo.size[0]}x{logo.size[1]} PNG data URI, {len(data)//1024} KB.")
    write_module(os.path.join(ROOT, "mobile", "src", "logo.js"), uri,
                 f"{logo.size[0]}x{logo.size[1]} PNG data URI, {len(data)//1024} KB.")
    print(f"  logo      {logo.size[0]}x{logo.size[1]}  {len(data)//1024} KB  -> web/src/logo.js, mobile/src/logo.js")

    # --- favicon: the round mark only (the top ~62% of the artwork) ---
    mark = master.crop((0, 0, w, round(h * 0.62)))
    side = max(mark.size)
    canvas = Image.new("RGBA", (side, side), (255, 255, 255, 255))
    canvas.paste(mark, ((side - mark.size[0]) // 2, (side - mark.size[1]) // 2), mark)
    icon = canvas.resize((FAVICON, FAVICON), Image.LANCZOS)
    out = os.path.join(ROOT, "web", "public", "favicon.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    icon.save(out, "PNG", optimize=True)
    print(f"  favicon   {FAVICON}x{FAVICON}  {os.path.getsize(out)//1024} KB  -> web/public/favicon.png")

if __name__ == "__main__":
    main()
